### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by MoonshineSG** [cheton/cnc#112]
Starting with version 1 grbl does not send descriptions for error messages and settings. It would be useful if there is some sort of "translation" done by cnc.js... 
All the codes descriptions are available at https://github.com/gnea/grbl-Mega/tree/edge/doc/csv

**Comment by cheton** [comment]
Added error messages in 1.8.14

![image](https://cloud.githubusercontent.com/assets/447801/21892990/2cefc9da-d914-11e6-8415-657608f89168.png)

**Comment by MoonshineSG** [comment]
Yes, it works as shown above. I see that ALARM and Settings, not yet implemented, but will be as well?

Would maybe be nicer if the error is displayed in a more "human" way (not that we don't read json) ?

Smth like:
```
Grbl 1.1e ['$' for help]
[MSG:'$H'|'$X' to unlock]
> M6
Error 9: G-code lock
```

or even

```
Grbl 1.1e ['$' for help]
[MSG:'$H'|'$X' to unlock]
> M6
G-code lock (error 9)
```

Maybe, a mouse over long description ("G-code commands are locked out during alarm or jog state.") which would benefit those starting to explore cnc ?

**Comment by cheton** [comment]
Detailed descriptions for ALARM and $$ will be implemented in a later version.

In my example above, I displayed additional error message in a well-formed json format `{"err":{...}}` that's because I want to differentiate translated result from Grbl's error message, especially showing the line number that caused an error while sending a g-code file.

![image](https://cloud.githubusercontent.com/assets/447801/21923555/b4a150ba-d9af-11e6-9d0d-b23519950e63.png)

Use a human readable format is fine with me for your suggestions, I will try to find a better format to display errors.
